apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vite-react-shadcn-ts-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: APP_IMAGE
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/vite-react-shadcn-ts
    newTag: 792373136340.dkr.ecr.us-west-2.amazonaws.com/vite-react-shadcn-ts:6a5d5ae

replicas:
  - name: vite-react-shadcn-ts
    count: 1

patches:
  - target:
      kind: Ingress
      name: vite-react-shadcn-ts
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vite-react-shadcn-ts-dev.agent.opsera.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: vite-react-shadcn-ts-dev.agent.opsera.dev
